# KANIA PUTRI ANANDA
# 2109106006
## PRAKTIKUM KECERDASAN BUATAN
## POSTTEST 7

# Import Library Tensorflow

In [2]:
import tensorflow as tf

# Random Tensor dengan Shape (5,5)

In [3]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[ 1.0646114 , -1.4799844 ,  0.22213589, -0.49064332, -1.219541  ],
       [ 1.1215402 ,  0.06602204,  0.08294114,  0.46999708, -0.3689432 ],
       [ 2.6591425 ,  0.4192372 , -0.5443427 , -0.9204076 , -1.7302604 ],
       [ 0.22460638, -0.5495416 , -1.1700286 , -0.05446782, -0.5820542 ],
       [-0.14167345,  1.4592743 ,  2.3417501 , -0.67573065, -0.52261186]],
      dtype=float32)

# Prime Tensor dengan Shape (5,5)

In [4]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47, 
                            53, 59, 61, 67, 71, 
                            73, 79, 83, 89, 97], shape=[5,5], dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

# Dimensi dari Random Tensor dan Prime Tensor

## Dimensi Random Tensor

In [7]:
dimensi_random = tf.constant(['random_tensor'], shape=[5,5])
dimensi_random.shape


TensorShape([5, 5])

In [8]:
tf.shape(dimensi_random)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

## Dimensi Prime Tensor

In [9]:
dimensi_prime = tf.constant(['prime_tensor'], shape=[5,5])
dimensi_prime.shape

TensorShape([5, 5])

In [ ]:
tf.shape(dimensi_prime)

# Perhitungan Aritmetika

### Penjumlahan

In [11]:
penjumlahan = random_tensor + prime_tensor
penjumlahan.numpy()

array([[ 3.0646114,  1.5200156,  5.222136 ,  6.5093565,  9.780459 ],
       [14.12154  , 17.066023 , 19.082941 , 23.469997 , 28.631058 ],
       [33.65914  , 37.41924  , 40.455658 , 42.079594 , 45.26974  ],
       [53.224606 , 58.45046  , 59.82997  , 66.94553  , 70.417946 ],
       [72.85833  , 80.459274 , 85.34175  , 88.32427  , 96.47739  ]],
      dtype=float32)

### Pengurangan

In [12]:
pengurangan = random_tensor - prime_tensor
pengurangan.numpy()

array([[ -0.93538857,  -4.4799843 ,  -4.777864  ,  -7.4906435 ,
        -12.219541  ],
       [-11.87846   , -16.933977  , -18.917059  , -22.530003  ,
        -29.368942  ],
       [-28.340858  , -36.58076   , -41.544342  , -43.920406  ,
        -48.73026   ],
       [-52.775394  , -59.54954   , -62.17003   , -67.05447   ,
        -71.582054  ],
       [-73.14167   , -77.540726  , -80.65825   , -89.67573   ,
        -97.52261   ]], dtype=float32)

### Perkalian

In [13]:
perkalian = random_tensor * prime_tensor
perkalian.numpy()

array([[  2.1292229,  -4.4399533,   1.1106794,  -3.4345033, -13.41495  ],
       [ 14.580023 ,   1.1223747,   1.5758816,  10.809933 , -10.699353 ],
       [ 82.43342  ,  15.511776 , -22.31805  , -39.577526 , -81.322235 ],
       [ 11.904139 , -32.422955 , -71.37174  ,  -3.6493437, -41.325848 ],
       [-10.342161 , 115.28267  , 194.36526  , -60.140026 , -50.69335  ]],
      dtype=float32)

### Pembagian

In [14]:
pembagian = random_tensor / prime_tensor
pembagian.numpy()

array([[ 0.5323057 , -0.49332812,  0.04442718, -0.0700919 , -0.11086736],
       [ 0.08627232,  0.00388365,  0.00436532,  0.02043466, -0.01272218],
       [ 0.08577879,  0.01133073, -0.01327665, -0.02140483, -0.03681405],
       [ 0.00423786, -0.00931426, -0.0191808 , -0.00081295, -0.00819795],
       [-0.00194073,  0.01847183,  0.02821386, -0.00759248, -0.00538775]],
      dtype=float32)

### Modulus

In [15]:
modulus = random_tensor % prime_tensor
modulus.numpy()

array([[1.0646114e+00, 1.5200156e+00, 2.2213589e-01, 6.5093565e+00,
        9.7804594e+00],
       [1.1215402e+00, 6.6022038e-02, 8.2941137e-02, 4.6999708e-01,
        2.8631058e+01],
       [2.6591425e+00, 4.1923720e-01, 4.0455658e+01, 4.2079594e+01,
        4.5269741e+01],
       [2.2460638e-01, 5.8450459e+01, 5.9829971e+01, 6.6945534e+01,
        7.0417946e+01],
       [7.2858330e+01, 1.4592743e+00, 2.3417501e+00, 8.8324272e+01,
        9.6477386e+01]], dtype=float32)

### Pemangkatan

In [16]:
pemangkatan = random_tensor ** prime_tensor
pemangkatan.numpy()

array([[ 1.13339746e+00, -3.24168944e+00,  5.40870940e-04,
        -6.84480742e-03, -8.87483501e+00],
       [ 4.44214678e+00,  8.60422610e-21,  2.86173715e-21,
         2.87202777e-08, -2.76583525e-13],
       [ 1.46889213e+13,  1.07402134e-14, -1.48172776e-11,
        -2.82584466e-02, -1.55324039e+11],
       [ 4.22056569e-35, -4.57123459e-16, -1.44538789e+04,
        -0.00000000e+00, -2.05306741e-17],
       [-0.00000000e+00,  9.26440594e+12,  4.69749283e+30,
        -7.07704180e-16, -4.60667998e-28]], dtype=float32)

### Pembagian Bulat

In [17]:
bagi_bulat = random_tensor // prime_tensor
bagi_bulat.numpy()

array([[ 0., -1.,  0., -1., -1.],
       [ 0.,  0.,  0.,  0., -1.],
       [ 0.,  0., -1., -1., -1.],
       [ 0., -1., -1., -1., -1.],
       [-1.,  0.,  0., -1., -1.]], dtype=float32)

# Nilai Maksimum dan Minimum

## Nilai Maksimum Random Tensor

In [21]:
max_random_tensor = tf.argmax(random_tensor, axis = 0)
print("Nilai Maksimum Random Tensor Berada Diindex ", max_random_tensor.numpy())

Nilai Maksimum Random Tensor Berada Diindex  [2 4 4 1 1]


## Nilai Minimum Random Tensor

In [22]:
min_random_tensor= tf.argmin(random_tensor, axis = 0)
print("Nilai Minimum Random Tensor Berada Diindex ", min_random_tensor.numpy())

Nilai Minimum Random Tensor Berada Diindex  [4 0 3 2 2]


# Sorting Descending

## Random Tensor

In [23]:
desc_random_tensor = tf.sort(random_tensor, direction="DESCENDING")
print("DESCENDING")
desc_random_tensor.numpy()

DESCENDING


array([[ 1.0646114 ,  0.22213589, -0.49064332, -1.219541  , -1.4799844 ],
       [ 1.1215402 ,  0.46999708,  0.08294114,  0.06602204, -0.3689432 ],
       [ 2.6591425 ,  0.4192372 , -0.5443427 , -0.9204076 , -1.7302604 ],
       [ 0.22460638, -0.05446782, -0.5495416 , -0.5820542 , -1.1700286 ],
       [ 2.3417501 ,  1.4592743 , -0.14167345, -0.52261186, -0.67573065]],
      dtype=float32)

## Prime Tensor

In [24]:
desc_prime_tensor = tf.sort(prime_tensor, direction="DESCENDING")
print("DESCENDING")
desc_prime_tensor.numpy()

DESCENDING


array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)